import { execFileSync } from "node:child_process";
import {
  createHash,
  generateKeyPairSync,
  privateDecrypt,
  constants,
} from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import * as backupCrypto from "./backup-crypto.js";
import {
  decodeAgeRecipient,
  encryptSourceAudio,
  encryptToAgeRecipient,
  opaqueObjectName,
  restoreSourceAudio,
  wrapDataKey,
  type BackupRecipients,
} from "./backup-crypto.js";

const workspace = mkdtempSync(join(tmpdir(), "cauli-backup-crypto-"));
afterAll(() => rmSync(workspace, { recursive: true, force: true }));

function ageAvailable() {
  try {
    execFileSync("age", ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

/**
 * A real offline identity, generated by the official tool the operator would
 * use, so the recipient under test is not one this code invented.
 */
function ageIdentity() {
  const identityPath = join(workspace, `identity-${crypto.randomUUID()}.txt`);
  execFileSync("age-keygen", ["-o", identityPath], { stdio: "ignore" });
  const recipient = execFileSync("age-keygen", ["-y", identityPath])
    .toString()
    .trim();
  return { identityPath, recipient };
}

// RSA-4096 generation is slow enough to be worth doing once for the file.
const kms = generateKeyPairSync("rsa", { modulusLength: 4096 });
const kmsPublicKeyPem = kms.publicKey
  .export({ type: "spki", format: "pem" })
  .toString();

const sampleRecipient =
  "age18m4055pa59f7cz07xf8uzhu9e6ykyl26taccljde405xeulmpv9sym64p7";

function recipients(overrides: Partial<BackupRecipients> = {}) {
  return {
    kmsPublicKeyPem,
    kmsKeyId: "arn:aws:kms:us-east-2:000000000000:key/cauli-backup",
    ageRecipient: sampleRecipient,
    keyVersion: 1,
    ...overrides,
  } satisfies BackupRecipients;
}

const sourceAudio = Buffer.from(
  "a Source Audio object standing in for one Call's authoritative media"
);

describe("Source Audio Backup encryption", () => {
  it("draws a distinct data key, nonce, and object name for every Call", () => {
    const first = encryptSourceAudio(sourceAudio, recipients());
    const second = encryptSourceAudio(sourceAudio, recipients());

    // Identical plaintext must not produce identical ciphertext, or the backup
    // target could tell that two Calls hold the same recording.
    expect(first.ciphertext.equals(second.ciphertext)).toBe(false);
    expect(first.ciphertextSha256).not.toBe(second.ciphertextSha256);
    expect(first.wrapped.kmsWrappedKey).not.toBe(second.wrapped.kmsWrappedKey);
    expect(first.wrapped.ageWrappedKey).not.toBe(second.wrapped.ageWrappedKey);
    expect(first.manifest.equals(second.manifest)).toBe(false);

    const names = new Set(Array.from({ length: 64 }, () => opaqueObjectName()));
    expect(names.size).toBe(64);
    for (const name of names) expect(name).toMatch(/^[0-9a-f]{64}$/);
  });

  it("reveals nothing about the Workspace or Call in what it stores", () => {
    const encrypted = encryptSourceAudio(sourceAudio, recipients());
    const stored = Buffer.concat([
      encrypted.ciphertext,
      encrypted.manifest,
      Buffer.from(encrypted.wrapped.kmsWrappedKey, "base64"),
      Buffer.from(encrypted.wrapped.ageWrappedKey, "base64"),
      Buffer.from(opaqueObjectName()),
    ]).toString("latin1");

    for (const leak of [
      "Source Audio",
      "audio/webm",
      "plaintextSha256",
      "00000000-0000-0000-0000-000000000001",
    ]) {
      expect(stored).not.toContain(leak);
    }
  });

  it("wraps one data key to both KMS and the offline age recipient", () => {
    const encrypted = encryptSourceAudio(sourceAudio, recipients());
    expect(encrypted.wrapped.keyVersion).toBe(1);

    // Only the KMS private half, which lives in AWS and not here, opens this.
    const unwrapped = privateDecrypt(
      {
        key: kms.privateKey,
        padding: constants.RSA_PKCS1_OAEP_PADDING,
        oaepHash: "sha256",
      },
      Buffer.from(encrypted.wrapped.kmsWrappedKey, "base64")
    );
    expect(unwrapped).toHaveLength(32);

    const restored = restoreSourceAudio({
      ciphertext: encrypted.ciphertext,
      manifest: encrypted.manifest,
      ciphertextSha256: encrypted.ciphertextSha256,
      dataKey: unwrapped,
    });
    expect(restored.sourceAudio.equals(sourceAudio)).toBe(true);
    expect(restored.manifest.plaintextBytes).toBe(sourceAudio.length);

    // The age copy carries the same key, so either path recovers the backup.
    expect(
      Buffer.from(encrypted.wrapped.ageWrappedKey, "base64").subarray(0, 21)
    ).toEqual(Buffer.from("age-encryption.org/v1"));
  });

  it("refuses to hold private wrapping material", () => {
    const privatePem = kms.privateKey
      .export({ type: "pkcs8", format: "pem" })
      .toString();
    expect(() =>
      wrapDataKey(Buffer.alloc(32), recipients({ kmsPublicKeyPem: privatePem }))
    ).toThrow(/only public wrapping material/);

    // Nothing in this module can undo a wrap, so a compromised worker can
    // create backups it is unable to read back.
    expect(
      Object.keys(backupCrypto).filter((name) =>
        /unwrap|decryptDataKey|privateKey/i.test(name)
      )
    ).toEqual([]);
  });

  it("rejects a tampered checksum, manifest, tag, or ciphertext", () => {
    const encrypted = encryptSourceAudio(sourceAudio, recipients());
    const dataKey = privateDecrypt(
      {
        key: kms.privateKey,
        padding: constants.RSA_PKCS1_OAEP_PADDING,
        oaepHash: "sha256",
      },
      Buffer.from(encrypted.wrapped.kmsWrappedKey, "base64")
    );
    const intact = {
      ciphertext: encrypted.ciphertext,
      manifest: encrypted.manifest,
      ciphertextSha256: encrypted.ciphertextSha256,
      dataKey,
    };
    expect(() => restoreSourceAudio(intact)).not.toThrow();

    const flip = (buffer: Buffer, index: number) => {
      const copy = Buffer.from(buffer);
      copy[index] = (copy[index] ?? 0) ^ 0x01;
      return copy;
    };

    expect(() =>
      restoreSourceAudio({
        ...intact,
        ciphertextSha256: createHash("sha256").update("wrong").digest("hex"),
      })
    ).toThrow(/checksum does not match/);

    // A ciphertext edit is caught by the checksum first and, once the checksum
    // is recomputed to agree with it, by the authentication tag.
    const editedCiphertext = flip(encrypted.ciphertext, 3);
    expect(() =>
      restoreSourceAudio({ ...intact, ciphertext: editedCiphertext })
    ).toThrow(/checksum does not match/);
    expect(() =>
      restoreSourceAudio({
        ...intact,
        ciphertext: editedCiphertext,
        ciphertextSha256: createHash("sha256")
          .update(editedCiphertext)
          .digest("hex"),
      })
    ).toThrow(/failed authentication/);

    expect(() =>
      restoreSourceAudio({ ...intact, manifest: flip(encrypted.manifest, 40) })
    ).toThrow(/manifest failed authentication/);

    // The manifest's first 12 bytes are the nonce and the next 16 its tag;
    // disturbing either must not yield a manifest anyone trusts.
    expect(() =>
      restoreSourceAudio({ ...intact, manifest: flip(encrypted.manifest, 14) })
    ).toThrow(/manifest failed authentication/);

    expect(() =>
      restoreSourceAudio({ ...intact, dataKey: flip(dataKey, 0) })
    ).toThrow(/failed authentication/);
  });

  it("versions every wrap so an old key stays usable until its backups are rewrapped", () => {
    const first = encryptSourceAudio(
      sourceAudio,
      recipients({ keyVersion: 3 })
    );
    expect(first.wrapped.keyVersion).toBe(3);

    const dataKey = privateDecrypt(
      {
        key: kms.privateKey,
        padding: constants.RSA_PKCS1_OAEP_PADDING,
        oaepHash: "sha256",
      },
      Buffer.from(first.wrapped.kmsWrappedKey, "base64")
    );

    // Rewrapping replaces the wrapping, never the ciphertext, so the stored
    // object and its checksum survive a recovery-key rotation untouched.
    const rotated = generateKeyPairSync("rsa", { modulusLength: 4096 });
    const rewrapped = wrapDataKey(
      dataKey,
      recipients({
        keyVersion: 4,
        kmsPublicKeyPem: rotated.publicKey
          .export({ type: "spki", format: "pem" })
          .toString(),
      })
    );
    expect(rewrapped.keyVersion).toBe(4);
    expect(rewrapped.kmsWrappedKey).not.toBe(first.wrapped.kmsWrappedKey);

    const viaRotatedKey = privateDecrypt(
      {
        key: rotated.privateKey,
        padding: constants.RSA_PKCS1_OAEP_PADDING,
        oaepHash: "sha256",
      },
      Buffer.from(rewrapped.kmsWrappedKey, "base64")
    );
    expect(
      restoreSourceAudio({
        ciphertext: first.ciphertext,
        manifest: first.manifest,
        ciphertextSha256: first.ciphertextSha256,
        dataKey: viaRotatedKey,
      }).sourceAudio.equals(sourceAudio)
    ).toBe(true);
  });

  it("rejects a recipient that is not a well-formed age public key", () => {
    // An identity is generated offline and sealed; it must never be mistaken
    // for the recipient the worker wraps to, so the prefix alone is enough to
    // refuse it. The stand-in below is deliberately not a key.
    const identityShapedButNotAKey = ["AGE", "SECRET", "KEY", "1REDACTED"].join(
      "-"
    );

    for (const malformed of [
      "age1invalid",
      identityShapedButNotAKey,
      // A recipient whose checksum no longer holds.
      sampleRecipient.replace(/.$/, "q"),
      "",
    ]) {
      expect(() => decodeAgeRecipient(malformed)).toThrow(/age recipient/);
    }
  });
});

describe.skipIf(!ageAvailable())(
  "Source Audio Backup age interoperability",
  () => {
    it("produces key material the official age binary decrypts", () => {
      const { identityPath, recipient } = ageIdentity();
      const dataKey = Buffer.from("0123456789abcdef0123456789abcdef", "utf8");

      const wrappedPath = join(workspace, "data-key.age");
      writeFileSync(wrappedPath, encryptToAgeRecipient(recipient, dataKey));

      // The offline recovery path is the standard tool reading a standard file.
      // Nothing Cauli wrote takes part in opening it.
      const recovered = execFileSync("age", [
        "--decrypt",
        "--identity",
        identityPath,
        wrappedPath,
      ]);
      expect(recovered.equals(dataKey)).toBe(true);
    });

    it("hands the offline identity a key that opens a real backup", () => {
      const { identityPath, recipient } = ageIdentity();
      const encrypted = encryptSourceAudio(
        sourceAudio,
        recipients({ ageRecipient: recipient })
      );

      const wrappedPath = join(workspace, "backup-key.age");
      writeFileSync(
        wrappedPath,
        Buffer.from(encrypted.wrapped.ageWrappedKey, "base64")
      );
      const dataKey = execFileSync("age", [
        "--decrypt",
        "--identity",
        identityPath,
        wrappedPath,
      ]);

      const restored = restoreSourceAudio({
        ciphertext: encrypted.ciphertext,
        manifest: encrypted.manifest,
        ciphertextSha256: encrypted.ciphertextSha256,
        dataKey,
      });
      expect(restored.sourceAudio.equals(sourceAudio)).toBe(true);
    });
  }
);
